osx_image: xcode13.2
language: swift
os: osx
xcode_workspace: Omos.xcworkspace
xcode_scheme: Omos
xcode_destination: platform=iOS Simulator,OS=15.0,name=iPhone 11
before_install:
- pod install
notifications:
  slack:
    rooms:
	- <Omos>:<ubTWQexgQpZOn0Cx3ZatGtib>#development
