osx_image: xcode13.2
language: swift
os: osx
xcode_workspace: Omos.xcworkspace
xcode_scheme: Omos
xcode_destination: platform=iOS Simulator,OS=15.0,name=iPhone 11
before_install:
- pod install
notifications:
  slack:
    rooms:
	- <Omos>:<ubTWQexgQpZOn0Cx3ZatGtib>#development
      secure: BHLebcwfE7NK86YecQK7Fw4oPulZaRMX46Aa+1706SLftqTPK8f9ktU1mi242fS7GWBMn2jwrICqSHbYNwRdoulEk6NrpvSWV2pxjEJk8KBjAKFBO90c5GSFD9/xQBlAP/wYBBfxMFPhF6Iz6YIZb64RcdL2aO7/UGmkywiUPxBPurY6lxRdB2w6giObQDlCCErMy/d0QoZpfuXs5FESmBM4Vh3yDfd9Y5cBOpYG6yZIkW0hsJSmw+kB0dyC5UX7suUeZRHcdSLZ0a7pooCu9U7gNlMXF0a4eqFJEBJb7H1VY8iGPfCE1usjrD2EFC6vFpkD95cq8gXN9HGPpNl5cjhwKuYbhpY1CvX3ZSQ23JBj8wpHQ/XwIZNGN/41i231cCQ/wTVrxKnkaqO9Y6xlS2HSy/ePxbVbgdnTPcmw7IdbVshrOPbq9lrjXUsvBoV54Rk9O4Klf1R4JxrwLYypw60Yfz+So/8nzQv4BgrE2SEWjBXA8HGiDs46i1AuPSjHirEIiBbq0b7fEXqFQGRQSaOmqFUzI8KqiuRdaj47SepEDEbFkD4BZmzks2k37mqbdv0qZ4Axm8hM77/y7CzYdNN5zwd+xU+uIifnTcRexwBA2lCsNy/uVl2bTOk36kkj1ncoTL60Yvvei4HjUd5eJWkcGBTUS0nsaVLdnTQgQwU=
